export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";


export const LOGOUT = "LOGOUT";

export const FEED_USER_DETAILS = "FEED_USER_DETAILS"
export const FEED_USER_DETAILS_ERROR = "FEED_USER_DETAILS_ERROR"